Imports System
Imports System.Collections.Generic
Imports System.Text

Namespace YTPMakerAdvanced
    Public NotInheritable Class VegasAdapter
        Private Sub New()
        End Sub

        Public Shared Function BuildVegas12Template(project As YtpProject) As String
            Dim sb As New StringBuilder()
            sb.AppendLine("' Sony Vegas Pro 12 Script Template")
            sb.AppendLine("' Auto-generated by YTP Maker Advanced")
            sb.AppendLine("' Project: " & project.ProjectName)
            sb.AppendLine("' Mode: " & project.Type.ToString())
            sb.AppendLine()
            sb.AppendLine("' TODO: Load media bins and apply generated keyframes")
            sb.AppendLine("' AutoKeyframeData:")

            For Each k As String In project.AutoKeyframeData
                sb.AppendLine("'   " & k)
            Next

            sb.AppendLine()
            sb.AppendLine("' Placeholder: Insert generated clips in order")
            sb.AppendLine("' Placeholder: Apply velocity envelopes for YTP Tennis rounds")
            sb.AppendLine("' Placeholder: Add beat-synced markers for YTPMV")
            Return sb.ToString()
        End Function

        Public Shared Function BuildInstructionSet(project As YtpProject) As List(Of String)
            Dim steps As New List(Of String)()
            steps.Add("Open Vegas Pro 12")
            steps.Add("Import generated clips from temp folder")
            steps.Add("Import final concat output")
            steps.Add("Apply AutoKeyframeData markers")
            If project.Type = ProjectType.YTPTennis Then
                steps.Add("Split rounds into alternating lanes for tennis response flow")
            End If
            If project.Type = ProjectType.YTPMV Then
                steps.Add("Snap marker grid to music BPM and align cut points")
            End If
            Return steps
        End Function
    End Class
End Namespace
